from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime, timedelta, timezone
import hashlib
import re
from typing import Any, Dict, Optional, Tuple
from zoneinfo import ZoneInfo

from .canvas import CanvasClient, CanvasItem
from .state import SyncState
from .trello import BoardLists, LabelInfo, TrelloClient

logger = logging.getLogger(__name__)

@dataclass(frozen=True)
class SyncSummary:
    lists_created: int
    cards_created: int
    cards_updated: int


def _course_list_name(course: Dict[str, Any]) -> str:
    course_id = int(course["id"])
    name = (course.get("name") or course.get("course_code") or f"Course {course_id}").replace("_", " ").strip()
    return name


def _build_desc(course_name: str, item: CanvasItem) -> str:
    kind = "Assignment" if item.item_type == "assignment" else "Event"
    lines = [f"Course: {course_name}", f"Type: {kind}", f"Canvas link: {item.url}"]

    if item.item_type == "assignment":
        pts = item.details.get("points_possible")
        if pts is not None:
            lines.append(f"Points: {pts}")
        submission_types = item.details.get("submission_types") or []
        if submission_types:
            lines.append(f"Submission types: {', '.join(map(str, submission_types))}")
        unlock_at = item.details.get("unlock_at")
        lock_at = item.details.get("lock_at")
        if unlock_at:
            lines.append(f"Unlocks: {unlock_at}")
        if lock_at:
            lines.append(f"Locks: {lock_at}")
        submitted = item.details.get("is_submitted")
        if submitted is True:
            lines.append("Status: Submitted/Graded (Canvas)")
    else:
        loc = item.details.get("location_name")
        if loc:
            lines.append(f"Location: {loc}")

    text = (item.details.get("description_text") or "").strip()
    if text:
        lines.append("")
        lines.append(text[:2000])

    lines.append("")
    lines.append("(Autogenerated from Canvas)")
    return "\n".join(lines)


def _detect_course_label(course: Dict[str, Any]) -> str:
    haystack = " ".join(
        str(x or "")
        for x in [
            course.get("course_code"),
            course.get("name"),
            course.get("sis_course_id"),
        ]
    )
    haystack = haystack.replace("_", " ")
    m = re.search(r"\b([A-Z]{3,4})\s+(\d{3})\b", haystack)
    if m:
        return f"{m.group(1)} {m.group(2)}"
    m2 = re.search(r"\b([A-Z]{3,4})\b", haystack)
    if m2:
        return m2.group(1)
    return (course.get("course_code") or course.get("name") or "COURSE").strip()[:20].upper()

def _desired_label_color(label_name: str, state: SyncState) -> str:
    palette = ["green", "yellow", "orange", "red", "purple", "blue", "sky", "lime", "pink"]
    mapping = state.meta.setdefault("label_colors", {})
    if isinstance(mapping, dict) and label_name in mapping:
        return str(mapping[label_name])

    used = set(str(c) for c in mapping.values()) if isinstance(mapping, dict) else set()
    for color in palette:
        if color not in used:
            mapping[label_name] = color
            return color

    h = hashlib.sha256(label_name.encode("utf-8")).digest()
    color = palette[h[0] % len(palette)]
    mapping[label_name] = color
    return color


def _parse_due(due_iso: Optional[str]) -> datetime:
    if not due_iso:
        return datetime.max.replace(tzinfo=timezone.utc)
    try:
        return datetime.fromisoformat(due_iso.replace("Z", "+00:00")).astimezone(timezone.utc)
    except Exception:
        return datetime.max.replace(tzinfo=timezone.utc)

def _due_equal(a: Optional[str], b: Optional[str]) -> bool:
    da = _parse_due(a)
    db = _parse_due(b)
    if da == datetime.max.replace(tzinfo=timezone.utc) and db == datetime.max.replace(tzinfo=timezone.utc):
        return True
    return int(da.timestamp()) == int(db.timestamp())

def _ensure_token_expiry(
    *,
    trello: TrelloClient,
    board_id: str,
    state: SyncState,
    existing_lists: BoardLists,
    existing_labels: Dict[str, LabelInfo],
    created_at_override: str,
    lifetime_days: int,
) -> None:
    created_str = (created_at_override or state.meta.get("canvas_token_created_at") or "").strip()
    if not created_str:
        created_str = date.today().isoformat()
        state.meta["canvas_token_created_at"] = created_str

    try:
        created_date = date.fromisoformat(created_str)
    except Exception:
        created_date = date.today()
        state.meta["canvas_token_created_at"] = created_date.isoformat()
    expires_date = created_date + timedelta(days=int(lifetime_days))
    days_left = (expires_date - date.today()).days

    token_list_name = "Canvas Token"
    token_list_id = state.meta.get("token_list_id") or ""
    if token_list_id and token_list_id not in existing_lists.by_id:
        token_list_id = ""

    if not token_list_id:
        created = token_list_name not in existing_lists.by_name
        token_list_id = trello.ensure_list(board_id, token_list_name, existing_lists, pos="top")
        state.meta["token_list_id"] = token_list_id
        if created:
            state.managed_list_ids[token_list_id] = True

    protected = state.meta.setdefault("protected_list_ids", [])
    if isinstance(protected, list) and token_list_id and token_list_id not in protected:
        protected.append(token_list_id)

    label_id = trello.ensure_label(board_id, "CANVAS", existing_labels, color="black")
    token_card_id = str(state.meta.get("token_card_id") or "")
    existing_card = trello.get_card(token_card_id) if token_card_id else None
    if token_card_id and existing_card is None:
        token_card_id = ""
    if token_card_id:
        if existing_card and existing_card.get("closed") is True:
            trello.set_card_closed(token_card_id, False)
        if existing_card and str(existing_card.get("idList") or "") != token_list_id:
            trello.move_card(token_card_id, token_list_id)
    else:
        name = "Canvas Token Expiry"
        desc = "Tracks when your Canvas access token expires.\n\n(Autogenerated)"
        card = trello.create_card(token_list_id, name, desc, None, label_ids=[label_id], pos="top")
        token_card_id = str(card["id"])
        state.meta["token_card_id"] = token_card_id

    due_iso = datetime.combine(expires_date, datetime.min.time(), tzinfo=timezone.utc).isoformat()
    title = f"Canvas token expires in {days_left} days ({expires_date.isoformat()})"
    desc = "\n".join(
        [
            f"Created: {created_date.isoformat()}",
            f"Lifetime: {int(lifetime_days)} days",
            f"Expires: {expires_date.isoformat()}",
            f"Days remaining: {days_left}",
            "",
            "(Autogenerated)",
        ]
    )
    trello.update_card(token_card_id, title, desc, due_iso)
    trello.add_label_to_card(token_card_id, label_id)
    if days_left <= 7:
        trello.set_card_cover_color(token_card_id, "red")
    elif days_left <= 30:
        trello.set_card_cover_color(token_card_id, "orange")
    else:
        trello.set_card_cover_color(token_card_id, "green")
    trello.set_card_pos_top(token_card_id)

    # Last sync card (created once, then updated in-place)
    last_sync_card_id = str(state.meta.get("last_sync_card_id") or "")
    last_sync_card = trello.get_card(last_sync_card_id) if last_sync_card_id else None
    if last_sync_card_id and last_sync_card is None:
        last_sync_card_id = ""
    if last_sync_card_id:
        if last_sync_card and last_sync_card.get("closed") is True:
            trello.set_card_closed(last_sync_card_id, False)
        if last_sync_card and str(last_sync_card.get("idList") or "") != token_list_id:
            trello.move_card(last_sync_card_id, token_list_id)
    else:
        card = trello.create_card(
            token_list_id,
            "Last Sync",
            "Tracks when this tool last ran.\n\n(Autogenerated)",
            None,
            label_ids=[label_id],
            pos="top",
        )
        last_sync_card_id = str(card["id"])
        state.meta["last_sync_card_id"] = last_sync_card_id

    try:
        now_et = datetime.now(ZoneInfo("America/New_York"))
    except Exception:
        now_et = datetime.now(timezone.utc)
    now_et_str = now_et.strftime("%m-%d-%y %I:%M%p").lstrip("0").replace("AM", "am").replace("PM", "pm")
    trello.update_card(
        last_sync_card_id,
        f"Last synced: {now_et_str}",
        f"Last successful sync run (ET): {now_et_str}\n\n(Autogenerated)",
        None,
    )
    trello.add_label_to_card(last_sync_card_id, label_id)
    trello.set_card_cover(last_sync_card_id, color="black", size="normal", brightness="dark")

def _ensure_todo_done_lists(*, trello: TrelloClient, board_id: str, state: SyncState, existing_lists: BoardLists) -> None:
    todo_name = "TODO"
    done_name = "Done"

    todo_id = str(state.meta.get("todo_list_id") or "")
    done_id = str(state.meta.get("done_list_id") or "")

    if todo_id and todo_id not in existing_lists.by_id:
        todo_id = ""
    if done_id and done_id not in existing_lists.by_id:
        done_id = ""

    if not todo_id:
        created = todo_name not in existing_lists.by_name
        todo_id = trello.ensure_list(board_id, todo_name, existing_lists, pos="bottom")
        state.meta["todo_list_id"] = todo_id
        if created:
            state.managed_list_ids[todo_id] = True

    if not done_id:
        created = done_name not in existing_lists.by_name
        done_id = trello.ensure_list(board_id, done_name, existing_lists, pos="bottom")
        state.meta["done_list_id"] = done_id
        if created:
            state.managed_list_ids[done_id] = True

    protected = state.meta.setdefault("protected_list_ids", [])
    if isinstance(protected, list):
        for lid in [todo_id, done_id]:
            if lid and lid not in protected:
                protected.append(lid)


def _ensure_course_info_card(
    *,
    canvas: CanvasClient,
    trello: TrelloClient,
    list_id: str,
    course: Dict[str, Any],
    label_id: str,
    label_name: str,
    label_color: str,
    state: SyncState,
) -> str:
    course_id = int(course["id"])
    existing_card_id = state.course_info_card.get(str(course_id))
    open_cards = trello.get_list_cards(list_id)
    open_card_ids = {str(c["id"]) for c in open_cards}

    title = f"{label_name} Class Info"

    course_code = str(course.get("course_code") or "").replace("_", " ").strip()
    course_name = str(course.get("name") or course_code or f"Course {course_id}").replace("_", " ").strip()

    term_name = ""
    try:
        cfull = canvas.get_course(course_id)
        term = cfull.get("term") or {}
        term_name = str(term.get("name") or "").strip()
    except Exception:
        term_name = ""

    teachers_lines = []
    try:
        teachers = canvas.get_course_teachers(course_id)
        for t in teachers:
            name = (t.get("name") or t.get("short_name") or t.get("sortable_name") or "").strip()
            email = (t.get("email") or "").strip()
            if name and email:
                teachers_lines.append(f"- {name} <{email}>")
            elif name:
                teachers_lines.append(f"- {name}")
    except Exception:
        teachers_lines = []

    desc_lines = [
        f"Course: {course_name}",
        f"Course code: {course_code}" if course_code else None,
        f"Term: {term_name}" if term_name else None,
        f"Start: {course.get('start_at')}" if course.get("start_at") else None,
        f"End: {course.get('end_at')}" if course.get("end_at") else None,
        "",
        "Professor / Teachers:" if teachers_lines else "Professor / Teachers: (not available via API)",
        *(teachers_lines or []),
        "",
        "(Autogenerated from Canvas)",
    ]
    desc = "\n".join([x for x in desc_lines if x is not None]).strip()

    if existing_card_id and existing_card_id in open_card_ids:
        trello.update_card(existing_card_id, title, desc, None)
        trello.add_label_to_card(existing_card_id, label_id)
        trello.set_card_cover(existing_card_id, color=label_color, size="full", brightness="dark")
        trello.set_card_pos_top(existing_card_id)
        return existing_card_id

    card = trello.create_card(list_id, title, desc, None, label_ids=[label_id], pos="top")
    card_id = str(card["id"])
    trello.set_card_cover(card_id, color=label_color, size="full", brightness="dark")
    trello.add_label_to_card(card_id, label_id)
    state.course_info_card[str(course_id)] = card_id
    return card_id


def sync_once(
    *,
    canvas: CanvasClient,
    trello: TrelloClient,
    board_id: str,
    due_within_days: int,
    canvas_term_id: str,
    canvas_token_created_at: str,
    canvas_token_lifetime_days: int,
    state: SyncState,
    log_texts: bool = False,
) -> Tuple[SyncState, SyncSummary]:
    existing_lists = trello.get_board_lists(board_id)
    existing_labels = trello.get_board_labels(board_id)
    _ensure_token_expiry(
        trello=trello,
        board_id=board_id,
        state=state,
        existing_lists=existing_lists,
        existing_labels=existing_labels,
        created_at_override=canvas_token_created_at,
        lifetime_days=canvas_token_lifetime_days,
    )
    _ensure_todo_done_lists(trello=trello, board_id=board_id, state=state, existing_lists=existing_lists)

    lists_created = 0
    cards_created = 0
    cards_updated = 0

    courses = canvas.get_active_courses()
    if canvas_term_id:
        enrollment_term_id = int(canvas_term_id)
    else:
        term_ids = [
            int(c["enrollment_term_id"])
            for c in courses
            if c.get("enrollment_term_id") is not None and str(c.get("enrollment_term_id")).isdigit()
        ]
        enrollment_term_id = max(term_ids) if term_ids else None

    if enrollment_term_id is not None:
        courses = [c for c in courses if int(c.get("enrollment_term_id") or -1) == enrollment_term_id]
    used_list_names: Dict[str, int] = {}

    for course in courses:
        course_id = int(course["id"])
        base_name = _course_list_name(course)
        label_name = _detect_course_label(course)
        label_color = _desired_label_color(label_name, state)
        label_id = trello.ensure_label(board_id, label_name, existing_labels, color=label_color)
        list_id = state.course_to_list.get(str(course_id))

        if list_id:
            list_name = base_name
        else:
            list_name = base_name
            if list_name in existing_lists.by_name:
                list_name = f"{base_name} ({course_id})"

            used_count = used_list_names.get(list_name, 0)
            used_list_names[list_name] = used_count + 1
            if used_count > 0:
                list_name = f"{list_name} - {used_count + 1}"

        if not list_id:
            created = list_name not in existing_lists.by_name
            list_id = trello.ensure_list(board_id, list_name, existing_lists)
            state.course_to_list[str(course_id)] = list_id
            if created:
                state.managed_list_ids[list_id] = True
            lists_created += 1
        else:
            if list_id not in existing_lists.by_id:
                created = list_name not in existing_lists.by_name
                list_id = trello.ensure_list(board_id, list_name, existing_lists)
                state.course_to_list[str(course_id)] = list_id
                if created:
                    state.managed_list_ids[list_id] = True
                lists_created += 1

        course_name = base_name
        info_card_id = _ensure_course_info_card(
            canvas=canvas,
            trello=trello,
            list_id=list_id,
            course=course,
            label_id=label_id,
            label_name=label_name,
            label_color=label_color,
            state=state,
        )

        for item in canvas.upcoming_items(course_id, within_days=due_within_days):
            if log_texts and item.details.get("description_sample"):
                logger.debug(
                    "canvas %s %s:%s desc_sample=%r",
                    item.item_type,
                    item.course_id,
                    item.item_id,
                    item.details.get("description_sample"),
                )
            if item.item_type == "assignment" and item.details.get("is_submitted") is True:
                # Completed in Canvas; don't create/update/resync.
                state.item_to_card.setdefault(item.key, {}).update(
                    {"status": "done", "locked": True, "checksum": item.checksum}
                )
                continue

            title = item.title
            desc = _build_desc(course_name, item)
            existing = state.item_to_card.get(item.key)
            if not existing or not existing.get("card_id"):
                card = trello.create_card(list_id, title, desc, item.due_iso, label_ids=[label_id])
                card_id = str(card["id"])
                trello.add_label_to_card(card_id, label_id)
                state.item_to_card[item.key] = {
                    "card_id": card_id,
                    "checksum": item.checksum,
                    "status": "active",
                    "locked": False,
                    "origin_list_id": list_id,
                    "last_seen_list_id": list_id,
                    "rendered_name": title,
                    "rendered_desc": desc,
                    "rendered_due": item.due_iso or "",
                }
                cards_created += 1
                continue

            if str(existing.get("status") or "") in {"done", "manual"} or existing.get("locked") is True:
                trello.add_label_to_card(existing["card_id"], label_id)
                continue

            card = trello.get_card(existing["card_id"])
            if card is None:
                # Card deleted manually; don't recreate automatically.
                existing["status"] = "manual"
                existing["locked"] = True
                continue
            if card.get("closed") is True:
                existing["status"] = "done"
                existing["locked"] = True
                continue

            existing["last_seen_list_id"] = str(card.get("idList") or "")
            origin = str(existing.get("origin_list_id") or "")
            if not origin:
                origin = list_id
                existing["origin_list_id"] = list_id
            if origin and str(card.get("idList") or "") != origin:
                existing["status"] = "manual"
                existing["locked"] = True
                trello.add_label_to_card(existing["card_id"], label_id)
                continue

            def _norm(s: str) -> str:
                return (s or "").replace("\r\n", "\n").strip()

            if not existing.get("rendered_name"):
                # First run after upgrade: attempt to detect manual edits without breaking legitimate Canvas updates.
                if existing.get("checksum") == item.checksum:
                    if _norm(str(card.get("name") or "")) != _norm(title) or _norm(str(card.get("desc") or "")) != _norm(
                        desc
                    ) or not _due_equal(str(card.get("due") or ""), item.due_iso or ""):
                        existing["status"] = "manual"
                        existing["locked"] = True
                        trello.add_label_to_card(existing["card_id"], label_id)
                        continue
                    existing["rendered_name"] = title
                    existing["rendered_desc"] = desc
                    existing["rendered_due"] = item.due_iso or ""
                else:
                    existing["rendered_name"] = str(card.get("name") or "")
                    existing["rendered_desc"] = str(card.get("desc") or "")
                    existing["rendered_due"] = str(card.get("due") or "")

            if _norm(str(card.get("name") or "")) != _norm(str(existing.get("rendered_name") or "")) or _norm(
                str(card.get("desc") or "")
            ) != _norm(str(existing.get("rendered_desc") or "")) or not _due_equal(
                str(card.get("due") or ""), str(existing.get("rendered_due") or "")
            ):
                existing["status"] = "manual"
                existing["locked"] = True
                trello.add_label_to_card(existing["card_id"], label_id)
                continue

            if existing.get("checksum") != item.checksum:
                trello.update_card(existing["card_id"], title, desc, item.due_iso, label_ids=[label_id])
                existing["checksum"] = item.checksum
                existing["rendered_name"] = title
                existing["rendered_desc"] = desc
                existing["rendered_due"] = item.due_iso or ""
                cards_updated += 1
            trello.add_label_to_card(existing["card_id"], label_id)

        # Sort cards top-to-bottom by due date (info card pinned at top).
        # Includes manually edited/moved-within-list cards and manually created cards.
        list_cards = trello.get_list_cards(list_id)
        sortable = []
        for idx, c in enumerate(list_cards):
            cid = str(c.get("id") or "")
            if not cid or cid == info_card_id:
                continue
            due = c.get("due")
            sortable.append((cid, _parse_due(due), idx))
        desired = [info_card_id] + [cid for (cid, _d, _i) in sorted(sortable, key=lambda t: (t[1], t[2]))]
        for cid in reversed(desired):
            trello.set_card_pos_top(cid)

    return state, SyncSummary(lists_created=lists_created, cards_created=cards_created, cards_updated=cards_updated)
